# Generated by Django 4.1.7 on 2023-02-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.BigIntegerField(unique=True, verbose_name='CPF'),
        ),
    ]
